### ISSUE TITLE
Regarding the reinstall the dependency 

### ISSUE THREAD

**Issue by rohitalate** [secure-systems-lab/lab-guidelines#22]
Hello Team,

I am trying to understand the Uptane demo code. but in that i am not able to understand why we need to reinstall the dependency. 
pip install --force-reinstall -r dev-requirements.txt
When we just do the even small print statement in uptane demo code. 
Kindly help me here i am new in this things.

Thanks in Advance.

**Comment by lukpueh** [comment]
This issue is probably a better fit for the Uptane repo. Transferring...

**Comment by lukpueh** [comment]
Oh, my bad. I can't transfer to another org. Would you mind re-submitting the issue at https://github.com/uptane/uptane? I'll close here.
