### ISSUE TITLE
Link to other documents

### ISSUE THREAD

**Issue by vladimir-v-diaz** [secure-systems-lab/lab-guidelines#5]
The README currently contains minimal information.  I propose we create links to the other documents and provide a brief outline of what they each cover.

**Comment by JustinCappos** [comment]
This makes sense to me.  Is something like the [collaboration page](https://ssl.engineering.nyu.edu/collaborate) a good starting point?

**Comment by aaaaalbert** [comment]
My understanding is that @vladimir-v-diaz wants to link to documents *in this repo*, as e.g. the [Seattle docs README](https://github.com/SeattleTestbed/docs/blob/master/README.md) does.

I'm putting together a draft like that Seattle one in [my fork](https://github.com/aaaaalbert/lab-guidelines/tree/fix-%235-improve-readme/).

**Comment by vladimir-v-diaz** [comment]
Both of you are correct.  I am proposing linking to the documents in this repository, similar to the 2nd paragraph of the collaboration page on the SSL website.
